USE master;
GO
ALTER DATABASE DevBlog SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE IF EXISTS DevBlog;
GO

CREATE DATABASE DevBlog;
GO
USE DevBlog;
GO


DROP TABLE IF EXISTS TimeRegistration;
CREATE TABLE TimeRegistration(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[UpdatedAt] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[CreatedAt] DATETIME NOT NULL DEFAULT GETUTCDATE()
);
GO

DROP TABLE IF EXISTS Account;
CREATE TABLE Account(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[FirstName] NVARCHAR(64) NOT NULL,
	[LastName] NVARCHAR(64) NOT NULL,
	[Email] NVARCHAR(320) NOT NULL,
	[Password] VARCHAR(60) NOT NULL,
	[IsAdmin] BIT NOT NULL DEFAULT 0,
	[TimeRegistrationId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TimeRegistration(Id)
);
GO

DROP TABLE IF EXISTS Category;
CREATE TABLE Category(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(64) NOT NULL
);
GO

DROP TABLE IF EXISTS Tag;
CREATE TABLE Tag(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(64) NOT NULL
);
GO

DROP TABLE IF EXISTS Post;
CREATE TABLE Post(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Title] NVARCHAR(64) NOT NULL,
	[Content] NVARCHAR(1024) NOT NULL,
	[AuthorId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
	[CategoryId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Category(Id),
	[PostType] TINYINT NOT NULL, -- 0: BlogPost | 1: PortfolioPost
	[TimeRegistrationId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TimeRegistration(Id)
);
GO

DROP TABLE IF EXISTS PostImage;
CREATE TABLE PostImage(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[PostId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Post(Id)
);
GO

DROP TABLE IF EXISTS PostTags;
CREATE TABLE PostTags(
	[PostId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Post(Id),
	[TagId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tag(Id),
	PRIMARY KEY([PostId], [TagId])
);

DROP TABLE IF EXISTS Comment;
CREATE TABLE Comment(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Content] NVARCHAR(1024) NOT NULL,
	[AuthorId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(Id),
	[PostId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Post(Id),
	[TimeRegistrationId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TimeRegistration(Id)
);
GO

